// just a demo
pkg product = 123 
{
  // get product list
  pkg get_list
  {
    // colors
    enum color : int {
      red   = 1,
      green = 2,
      blue  = 3
    }

    def in  = 1 {
      cat_id   : uint,      // category
      page_num : uint       // page number
    }

    def out = 2 {
      products : list {
        id    : uint,
        name  : string,
        color : enum<color>
      }
    }
  }
}
